# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT

name: APM Beta Pre-Release
on:
  workflow_dispatch:
jobs:
  BuildAndUpload:
    uses: ./.github/workflows/test-build.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      ContainerRepositoryNameAndTag: "apm-beta-pre-release:latest"
      BucketKey: "apm-beta-pre-release"
      PackageBucketKey: "apm-beta-pre-release"
