# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT

name: NonProd Release
on:
  workflow_dispatch:
jobs:
  BuildAndUpload:
    uses: ./.github/workflows/test-build.yml
    secrets: inherit
    permissions:
      id-token: write
      contents: read
    with:
      ContainerRepositoryNameAndTag: "ccwa_nonprod:latest"
      BucketKey: "nonprod"
      PackageBucketKey: "nonprod"